language: node_js

node_js:
  - "12"
  - "10"

script:
  - npm run lint
  - npm run build
  - "npm run test:es5"
  - npm run test
  - "npm run test:perf"
  - cd website && npm install && npm run build

after_success:
  - npx codecov

cache:
  directories:
    - "$HOME/.npm"
